apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # also do load balancing, but will not be exposed to outside of the Cluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
