apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: thangtran3112/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.99.104.252" # kubectl get services
              value: "auth-service.default" # <SERVICE_NAME>.<NAMESPACE> or kubectl get namespaces
