apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer # public facing, reachable from outside of the cluster
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
