apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    # matchLabels will match both labels of `app` and `tier` for all matching pods
    matchLabels:
      app: second-app
      tier: backend
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: thangtran3112/kub-first-app:2
        # - name: ...
        #   image: ...
